FreeTable/Models/Admin.cs
namespace FreeTable.Models
{
    public class Admin : IUsuario
    {
        public string? Nombre;

        public Admin() { } 
    }
}

FreeTable/Models/ErrorViewModel.cs
namespace FreeTable.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FreeTable/Models/Gestor.cs
namespace FreeTable.Models
{
    public class Gestor : IUsuario
    {
        public string? Correo;
        public string? Nombre;
        public int? Telefono;

        public Gestor() { }
    }
}

FreeTable/Models/IUsuario.cs
namespace FreeTable.Models
{
    public interface IUsuario
    {
        
    }
}

FreeTable/Models/NamePaths.cs
namespace FreeTable.Models
{
    public class NamePaths
    {
        public static string NamePathJson = "C:\\Users\\ycamacho\\Desktop\\Net-WorkSpace\\FreeTable\\wwwroot\\json\\";
        public static string NamePathImg = "C:\\Users\\ycamacho\\Desktop\\Net-WorkSpace\\FreeTable\\wwwroot\\img\\Restaurantes\\";


    }
}

FreeTable/Models/Reserva.cs
namespace FreeTable.Models
{
    public class Reserva
    {
        public int Id { get; set; }
        public int NumPersonas { get; set; }
        public DateTime Fecha { get; set; }
        public string? Hora { get; set; }
        public int Status { get; set; }

        public Reserva() {
            
        }

    }
}

FreeTable/Models/Restaurante.cs
namespace FreeTable.Models
{
    public class Restaurante :  IUsuario
    {
        public string? Cif { get; set; }
        public string? Gestor { get; set; }
        public string? Nombre { get; set; }
        public string? Correo { get; set; }
        public string? Direccion { get; set; }
        public int? Telefono { get; set; }
        public string? Description { get; set; }
        public int? CapacidadMax { get; set; }
        public string? JsonName { get; set; }

        public Restaurante() { }

        public Restaurante(string cif, string gestor, string nombre, string? correo, string? direccion, int? telefono, string? description, int? capacidadMax)
        {
            Cif = cif;
            Gestor = gestor;
            Nombre = nombre;
            Correo = correo;
            Direccion = direccion;
            Telefono = telefono;
            Description = description;
            CapacidadMax = capacidadMax;
            AssingJsonName(nombre);
        }

        private void AssingJsonName(string jsonName)
        {
            this.JsonName = jsonName.ToLower().Trim();
        }
    }
}

FreeTable/Controllers/HomeController.cs
using FreeTable.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FreeTable.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FreeTable/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace FreeTable.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
    }
}

FreeTable/Controllers/RestauranteController.cs
using FreeTable.Models;
using Microsoft.AspNetCore.Mvc;

namespace FreeTable.Controllers
{
    public class RestauranteController : Controller
    {
        public IActionResult Index()
        {
            Restaurante r = new("A123454678", 
                "yosarca@gmail.com", 
                "churrasicparck", 
                "churros.park@gmail.com", 
                "Cll atras", 624527327, 
                "Churros en un parque", 150 );

            return View(r);
        }

        public IActionResult Privacy()
        {
            Restaurante r = new("A123454678",
                "yosarca@gmail.com",
                "Churrasic Parck",
                "churros.park@gmail.com",
                "Cll atras", 624527327,
                "Churros en un parque", 150);

            return View(r);
        }


    }
}

FreeTable/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;

namespace FreeTable.Controllers
{
    public class UsuarioController : Controller
    {
        public IActionResult Cliente()
        {
            return View();
        }

        public IActionResult Restaurante()
        {
            return View();
        }

    }
}

FreeTable/Views/Login/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>

<form action="/" method="post">

    <label>
        Usuario: 
        <input type="type" name="name" value="" />
    </label>
    <label>
        Contraseña: 
        <input type="type" name="name" value="" />
    </label>
    <input type="submit" name="login" value="Iniciar sesión" />
</form>

FreeTable/Views/Restaurante/Index.cshtml
@model Restaurante

@{
    ViewData["Title"] = "Home Page";

    

}



<h1>@Model.Nombre</h1>

FreeTable/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FreeTable</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="icon" type="image/x-icon" href="~/favicon.svg">
    @await RenderSectionAsync("Css", false);
    @* <link rel="stylesheet" href="~/FreeTable.styles.css" asp-append-version="true" /> *@
</head>
<body>
    <header class="header-principal">
        <nav class="nav">
            <div class="nav-logo">
                <a asp-controller="Restaurante" asp-action="Index" ><img src="~/img/logo.svg" alt="Freetable logo" /></a>
            </div>
            <div class="nav-form">
                <form action="/" method="post" class="form-query">
                    <div class="form-res">
                        <input type="text" name="fecha" placeholder="10/02/2024" value="" />
                        <input type="text" id="inp-border" name="hora" placeholder="20:30" value="" />
                        <input type="text" name="personas" placeholder="2 Personas" value="" />
                    </div>
                    <div class="form-rest">
                        <input type="text" name="rest" placeholder="Restaurante" value="" />
                        <input type="submit" name="buscar" value="Buscar" />
                    </div>
                </form>
            </div>
            <div class="nav-btt">
                <a asp-controller="Usuario" asp-action="Cliente" class="btt-3" >Registrarse</a>
                <a asp-controller="Login" asp-action="Login" class="btt-1" >Iniciar Sesión</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 contenido">
            @RenderBody()
        </main>
    </div>

    <footer class="foo">
        <div class="foo-acount">
            <h3>¿Tines un resturante?</h3>
            <p>
                Estamos interesados en ampliar nuestro catálogo. Si eres dueño de un restaurante y quieres 
                trabajar con nosotros, el primer paso es crear una cuenta de empresa. Què esperas?
            </p>
            <a href="#" class="btt-2 mh-auto">Registrarse</a>
        </div>
        <div class="foo-social">
            <h3>Síguenos en nuestras redes sociales</h3>
            <nav class="nav-social">
                <a href="#"><img src="~/img/facebook.svg" alt="Alternate Text" /></a>
                <a href="#"><img src="~/img/instagram.svg" alt="Alternate Text" /></a>
                <a href="#"><img src="~/img/twiter.svg" alt="Alternate Text" /></a>
            </nav>
            <p class="foo-info" >
                Para más información llamar al 624527327 <br />
                o enviar un correo a freetable.atencion@gmail.com
            </p>
        </div>
    </footer>
    @* <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script> *@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FreeTable/Views/Usuario/Cliente.cshtml
@section Css {
    <link rel="stylesheet" href="..\css\RegistroCliente.css"></link>
}

@{
}

<h2>Resgistro</h2>

<form class="form-registre-client">
    <input type="text" name="numberphone" value="" placeholder="Número de teléfono" />
    <input type="email" name="email" value="" placeholder="Email" />
    <input type="text" name="names" value="" placeholder="Nobre y apellidos"/>
    <input type="text" name="pssw" value="" placeholder="Contraseña" />
    <input type="text" name="psswrepeat" value="" placeholder="Confirmar contraseña" />
    <input type="submit" asp-controller="" asp-action="" value="Registrarse"/>
</form>

<h3>Representas un restaurante?</h3>

<p>
    Si tienes un restaurante y quieres disfrutar de los beneficios que FreeTable tiene para ofreserte.
    Crea una cuenta como <a asp-controller="Usuario" asp-action="Restaurante">empresa aquí</a>.
</p>

FreeTable/Views/Usuario/Gestor.cshtml
@{
    ViewData["Title"] = "Gestor";
}

<h1>Gestor</h1>

FreeTable/Views/Usuario/Restaurante.cshtml
@{
    ViewData["Title"] = "Restaurante Registro";
}

<h1>Registro de empresa</h1>

<p>
    Agradecemos que decidas confiar en nosotros. Completa el formulario con los datos
    de tu empresa y en seguida te enviamo tu usuario y contraseña al correo que indiques.
</p>

<div class="form-gestor">
    <form action="/" method="post">
        <h2>Datos de usuario</h2>
        <lab>
            <input type="text" name="email" value="" />
        </lab>
        <lab>
            <input type="type" name="name" value="" />
        </lab>
        <lab>
            <input type="type" name="pssw" value="" />
        </lab>
        <lab>
            <input type="type" name="psswRepeat" value="" />
        </lab>

        <input type="submit" name="name" value="Continuar" />
    </form>

</div>

<div class="form-restaurant">
    <form action="/" method="post">
        <div>
            <h2>Datos de empresa</h2>
            <lab>
                <input type="type" name="name" value="" />
            </lab>
            <lab>
                <input type="type" name="name" value="" />
            </lab>
            <lab>
                <input type="type" name="name" value="" />
            </lab>
            <lab>
                <input type="type" name="name" value="" />
            </lab>
        </div>

        <input type="submit" name="name" value="Registrarse" />
    </form>
</div>